name: Build RISC-V Kernel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install RISC-V Toolchain
        run: |
          sudo apt update
          sudo apt install -y gcc-riscv64-unknown-elf

      - name: Install QEMU
        run: |
          sudo apt install -y qemu-system-misc

      - name: Build kernel
        run: make
      
      - name: Run QEMU boot test
        run: |
          chmod +x scripts/test_boot.sh
          ./scripts/test_boot.sh

